<div class="card card-block">
    <h4 class="card-title">Cadastrar Cliente</h4>
    <p class="card-text">Preencha o formulário para cadastrar um cliente.</p>
    <form>
        <div class="row">
            <div class="col-xs-3 col-md-3">
                <div class="form-group">
                    <label for="nomeCliente">Nome</label>
                    <input type="text" class="form-control" id="nomeCliente">
                </div>
            </div>
            <div class="col-xs-3 col-md-3">
                <div class="form-group">
                    <label for="emailCliente">E-mail</label>
                    <input type="email" class="form-control" id="emailCliente">
                </div>
            </div>
            <div class="col-xs-3 col-md-3">
                <div class="form-group">
                    <label for="telCliente">Telefone</label>
                    <input type="tel" class="form-control" id="telCliente">
                </div>
            </div>
            <div class="col-xs-3 col-md-3">
                <div class="form-group">
                    <label for="logCliente">Logradouro</label>
                    <input type="text" class="form-control" id="logCliente">
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-xs-3 col-md-3">
                <div class="form-group">
                    <label for="numeroCliente">Número</label>
                    <input type="text" class="form-control" id="numeroCliente">
                </div>
            </div>
            <div class="col-xs-3 col-md-3">
                <div class="form-group">
                    <label for="bairroCliente">Bairro</label>
                    <input type="text" class="form-control" id="bairroCliente">
                </div>
            </div>
            <div class="col-xs-3 col-md-3">
                <div class="form-group">
                    <label for="cidadeCliente">Cidade</label>
                    <input type="text" class="form-control" id="cidadeCliente">
                </div>
            </div>
            <div class="col-xs-3 col-md-3">
                <div class="form-group">
                    <label for="ufCliente">UF</label>
                    <input type="text" class="form-control" id="ufCliente">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-3 col-md-3">
                <div class="form-group">
                    <button type="button" class="btn btn-success">Cadastrar</button>
                </div>
            </div>
        </div>
    </form>
</div>

<div class="card card-block">
    <h4 class="card-title">Deletar Cliente</h4>
    <p class="card-text">Informe o código do cliente a ser deletado.</p>
    <form>
        <div class="row">
            <div class="col-xs-3 col-md-3">
                <div class="form-group">
                    <label for="codDeleteCliente">Código</label>
                    <input type="text" class="form-control" id="codDeleteCliente">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-3 col-md-3">
                <div class="form-group">
                    <button type="button" class="btn btn-danger">Deletar</button>
                </div>
            </div>
        </div>
    </form>
</div>

<div class="card card-block">
    <h4 class="card-title">Editar Cliente</h4>
    <p class="card-text">Informe o código do cliente a ser editado.</p>
    <form>
        <div class="row">
            <div class="col-xs-3 col-md-3">
                <div class="form-group">
                    <label for="codEditarCliente">Código</label>
                    <input type="text" class="form-control" id="codEditarCliente">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-3 col-md-3">
                <div class="form-group">
                    <label for="nomeEditarCliente">Nome</label>
                    <input type="text" class="form-control" id="nomeEditarCliente">
                </div>
            </div>
            <div class="col-xs-3 col-md-3">
                <div class="form-group">
                    <label for="emailEditarCliente">E-mail</label>
                    <input type="email" class="form-control" id="emailEditarCliente">
                </div>
            </div>
            <div class="col-xs-3 col-md-3">
                <div class="form-group">
                    <label for="telEditarCliente">Telefone</label>
                    <input type="tel" class="form-control" id="telEditarCliente">
                </div>
            </div>
            <div class="col-xs-3 col-md-3">
                <div class="form-group">
                    <label for="logEditarCliente">Logradouro</label>
                    <input type="text" class="form-control" id="logEditarCliente">
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-xs-3 col-md-3">
                <div class="form-group">
                    <label for="numeroEditarCliente">Número</label>
                    <input type="text" class="form-control" id="numeroEditarCliente">
                </div>
            </div>
            <div class="col-xs-3 col-md-3">
                <div class="form-group">
                    <label for="bairroEditarCliente">Bairro</label>
                    <input type="text" class="form-control" id="bairroEditarCliente">
                </div>
            </div>
            <div class="col-xs-3 col-md-3">
                <div class="form-group">
                    <label for="cidadeEditarCliente">Cidade</label>
                    <input type="text" class="form-control" id="cidadeEditarCliente">
                </div>
            </div>
            <div class="col-xs-3 col-md-3">
                <div class="form-group">
                    <label for="ufEditarCliente">UF</label>
                    <input type="text" class="form-control" id="ufEditarCliente">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-3 col-md-3">
                <div class="form-group">
                    <button type="button" class="btn btn-success">Buscar</button>
                    <button type="button" class="btn btn-success">Editar</button>
                </div>
            </div>
        </div>
    </form>
</div>

<div class="card card-block">
    <h4 class="card-title">Lista de Clientes</h4>
    <p class="card-text">Lista de todos os clientes cadastrados.</p>
</div>